<?php
include 'includes/init.php'; require_role(['Admin','Manager']); $message=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
  $code=trim($_POST['code']??'');$name=trim($_POST['name']??'');$type=$_POST['type']??'';
  $normal=in_array($type,['Asset','Expense'],true)?'Debit':'Credit';
  if(!preg_match('/^[0-9]{3,10}$/',$code)||$name===''||!in_array($type,['Asset','Liability','Equity','Revenue','Expense'],true))$message=['Enter a valid account code, name and type.','danger'];
  else try{$stmt=$conn->prepare('INSERT INTO accounts(code,name,type,normal_balance) VALUES(?,?,?,?)');$stmt->execute([$code,$name,$type,$normal]);audit('create','account',(int)$conn->lastInsertId(),['code'=>$code]);$message=['Account created.','success'];}catch(Throwable $e){$message=['Account code already exists or data is invalid.','danger'];}
}
$accounts=$conn->query('SELECT a.*,COALESCE(SUM(jl.debit-jl.credit),0) raw_balance FROM accounts a LEFT JOIN journal_lines jl ON jl.account_id=a.id LEFT JOIN journal_entries je ON je.id=jl.journal_entry_id AND je.status="Posted" GROUP BY a.id ORDER BY a.code')->fetchAll();
?>
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h3>Chart of Accounts</h3><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#accountModal">New Account</button></div><div class="alerts"><?php if($message)showMessage($message);?></div><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Normal Balance</th><th class="text-end">Balance</th><th>Status</th></tr></thead><tbody><?php foreach($accounts as $a):$balance=$a['normal_balance']==='Credit'?-$a['raw_balance']:$a['raw_balance'];?><tr><td class="fw-semibold"><?=escape($a['code'])?></td><td><?=escape($a['name'])?></td><td><span class="badge bg-label-primary"><?=escape($a['type'])?></span></td><td><?=escape($a['normal_balance'])?></td><td class="text-end"><?=money($balance)?></td><td><?=escape($a['status'])?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="accountModal"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h5>New Account</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>"><div class="mb-3"><label class="form-label">Code</label><input name="code" class="form-control" placeholder="e.g. 5300" required></div><div class="mb-3"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="mb-3"><label class="form-label">Type</label><select name="type" class="form-select"><?php foreach(['Asset','Liability','Equity','Revenue','Expense'] as $t):?><option><?=$t?></option><?php endforeach;?></select></div></div><div class="modal-footer"><button class="btn btn-primary">Create Account</button></div></form></div></div>
<?php include 'includes/footer.php';?>
