<?php
include 'includes/init.php';require_role(['Admin','Manager']);$message=[];$accounts=$conn->query("SELECT id,code,name FROM accounts WHERE status='Active' ORDER BY code")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
 $amount=(float)($_POST['amount']??0);$debit=(int)($_POST['debit_account']??0);$credit=(int)($_POST['credit_account']??0);$date=$_POST['entry_date']??'';$desc=trim($_POST['description']??'');
 if($amount<=0||$debit===$credit||!$debit||!$credit||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$desc==='')throw new RuntimeException('Complete all fields with two different accounts.');
 $conn->beginTransaction();$sourceId=random_int(100000000,999999999);$id=post_journal($date,$desc,'manual',$sourceId,[['account_id'=>$debit,'debit'=>$amount],['account_id'=>$credit,'credit'=>$amount]]);audit('create','journal_entry',$id);$conn->commit();$message=['Journal entry posted.','success'];
 }catch(Throwable $e){if($conn->inTransaction())$conn->rollBack();$message=[$e->getMessage(),'danger'];}}
$entries=$conn->query("SELECT je.*,u.FullName,GROUP_CONCAT(CONCAT(a.code,' ',a.name,': D ',FORMAT(jl.debit,2),' / C ',FORMAT(jl.credit,2)) ORDER BY jl.id SEPARATOR ' | ') lines,SUM(jl.debit) total FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id JOIN accounts a ON a.id=jl.account_id LEFT JOIN users u ON u.id=je.user_id GROUP BY je.id ORDER BY je.entry_date DESC,je.id DESC LIMIT 200")->fetchAll();
?>
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h3>General Journal</h3><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#journalModal">Post Entry</button></div><div class="alerts"><?php if($message)showMessage($message);?></div><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Entry</th><th>Date</th><th>Description</th><th>Lines</th><th class="text-end">Total</th><th>Status</th></tr></thead><tbody><?php foreach($entries as $e):?><tr><td><?=escape($e['entry_no'])?></td><td><?=escape($e['entry_date'])?></td><td><?=escape($e['description'])?><br><small class="text-muted"><?=escape($e['source_type'])?></small></td><td><small><?=escape($e['lines'])?></small></td><td class="text-end"><?=money($e['total'])?></td><td><span class="badge bg-label-success"><?=escape($e['status'])?></span></td></tr><?php endforeach;?><?php if(!$entries):?><tr><td colspan="6" class="text-center py-4">No journal entries.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="modal fade" id="journalModal"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h5>Manual Journal Entry</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>"><div class="mb-3"><label class="form-label">Date</label><input type="date" name="entry_date" value="<?=date('Y-m-d')?>" class="form-control" required></div><div class="mb-3"><label class="form-label">Description</label><input name="description" class="form-control" required></div><?php foreach(['debit_account'=>'Debit Account','credit_account'=>'Credit Account'] as $n=>$l):?><div class="mb-3"><label class="form-label"><?=$l?></label><select name="<?=$n?>" class="form-select" required><option value="">Select account</option><?php foreach($accounts as $a):?><option value="<?=$a['id']?>"><?=escape($a['code'].' - '.$a['name'])?></option><?php endforeach;?></select></div><?php endforeach;?><div><label class="form-label">Amount</label><input type="number" min="0.01" step="0.01" name="amount" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Post Balanced Entry</button></div></form></div></div>
<?php include 'includes/footer.php';?>
