<?php
include 'includes/init.php';
require_role(['Admin','Manager']);
$from = preg_match('/^\d{4}-\d{2}-\d{2}$/', $_GET['from'] ?? '') ? $_GET['from'] : date('Y-m-01');
$to = preg_match('/^\d{4}-\d{2}-\d{2}$/', $_GET['to'] ?? '') ? $_GET['to'] : date('Y-m-d');
$incomeStmt=$conn->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE DATE(PaymentDate) BETWEEN ? AND ?'); $incomeStmt->execute([$from,$to]); $income=(float)$incomeStmt->fetchColumn();
$expenseStmt=$conn->prepare('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE expense_date BETWEEN ? AND ?'); $expenseStmt->execute([$from,$to]); $expense=(float)$expenseStmt->fetchColumn();
$unpaidStmt=$conn->prepare("SELECT COALESCE(SUM(c.Price-COALESCE(p.paid,0)),0) FROM charges c LEFT JOIN (SELECT charge_id,SUM(amount) paid FROM payments GROUP BY charge_id)p ON p.charge_id=c.id WHERE DATE(c.date) BETWEEN ? AND ? AND c.status!='Void'"); $unpaidStmt->execute([$from,$to]); $unpaid=(float)$unpaidStmt->fetchColumn();
$attendanceStmt=$conn->prepare('SELECT COUNT(*) FROM attendance WHERE DATE(check_in) BETWEEN ? AND ?'); $attendanceStmt->execute([$from,$to]); $visits=(int)$attendanceStmt->fetchColumn();
$dailyStmt=$conn->prepare("SELECT d.day, SUM(d.income) income, SUM(d.expense) expense FROM (SELECT DATE(PaymentDate) day, amount income, 0 expense FROM payments WHERE DATE(PaymentDate) BETWEEN ? AND ? UNION ALL SELECT expense_date day,0,amount FROM expenses WHERE expense_date BETWEEN ? AND ?)d GROUP BY d.day ORDER BY d.day"); $dailyStmt->execute([$from,$to,$from,$to]); $daily=$dailyStmt->fetchAll();
?>
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><h3>Financial & Gym Reports</h3><button onclick="window.print()" class="btn btn-outline-primary"><i class="bx bx-printer"></i> Print / PDF</button></div>
<div class="card mb-4"><div class="card-body"><form class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">From</label><input type="date" name="from" value="<?= escape($from) ?>" class="form-control"></div><div class="col-md-4"><label class="form-label">To</label><input type="date" name="to" value="<?= escape($to) ?>" class="form-control"></div><div class="col-md-4"><button class="btn btn-primary w-100">Apply Date Filter</button></div></form></div></div>
<div class="row"><div class="col-md-3 mb-4"><div class="card h-100"><div class="card-body"><small>Total Income</small><h3 class="text-success mt-2"><?= money($income) ?></h3></div></div></div><div class="col-md-3 mb-4"><div class="card h-100"><div class="card-body"><small>Total Expenses</small><h3 class="text-danger mt-2"><?= money($expense) ?></h3></div></div></div><div class="col-md-3 mb-4"><div class="card h-100"><div class="card-body"><small>Net Profit</small><h3 class="mt-2"><?= money($income-$expense) ?></h3></div></div></div><div class="col-md-3 mb-4"><div class="card h-100"><div class="card-body"><small>Outstanding / Visits</small><h5 class="mt-2"><?= money($unpaid) ?> · <?= $visits ?> visits</h5></div></div></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">Daily Summary</h5></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th class="text-end">Income</th><th class="text-end">Expense</th><th class="text-end">Net</th></tr></thead><tbody><?php foreach($daily as $d): ?><tr><td><?= escape($d['day']) ?></td><td class="text-end text-success"><?= money($d['income']) ?></td><td class="text-end text-danger"><?= money($d['expense']) ?></td><td class="text-end fw-semibold"><?= money($d['income']-$d['expense']) ?></td></tr><?php endforeach; ?><?php if(!$daily): ?><tr><td colspan="4" class="text-center py-4 text-muted">No transactions in selected period.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include 'includes/footer.php'; ?>
